# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter/CMakeFiles /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lisp

# Build rule for target.
lisp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lisp
.PHONY : lisp

# fast build rule for target.
lisp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/build
.PHONY : lisp/fast

builtins.o: builtins.cpp.o
.PHONY : builtins.o

# target to build an object file
builtins.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/builtins.cpp.o
.PHONY : builtins.cpp.o

builtins.i: builtins.cpp.i
.PHONY : builtins.i

# target to preprocess a source file
builtins.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/builtins.cpp.i
.PHONY : builtins.cpp.i

builtins.s: builtins.cpp.s
.PHONY : builtins.s

# target to generate assembly for a file
builtins.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/builtins.cpp.s
.PHONY : builtins.cpp.s

error.o: error.cpp.o
.PHONY : error.o

# target to build an object file
error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/error.cpp.o
.PHONY : error.cpp.o

error.i: error.cpp.i
.PHONY : error.i

# target to preprocess a source file
error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/error.cpp.i
.PHONY : error.cpp.i

error.s: error.cpp.s
.PHONY : error.s

# target to generate assembly for a file
error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/error.cpp.s
.PHONY : error.cpp.s

eval_env.o: eval_env.cpp.o
.PHONY : eval_env.o

# target to build an object file
eval_env.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/eval_env.cpp.o
.PHONY : eval_env.cpp.o

eval_env.i: eval_env.cpp.i
.PHONY : eval_env.i

# target to preprocess a source file
eval_env.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/eval_env.cpp.i
.PHONY : eval_env.cpp.i

eval_env.s: eval_env.cpp.s
.PHONY : eval_env.s

# target to generate assembly for a file
eval_env.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/eval_env.cpp.s
.PHONY : eval_env.cpp.s

files.o: files.cpp.o
.PHONY : files.o

# target to build an object file
files.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/files.cpp.o
.PHONY : files.cpp.o

files.i: files.cpp.i
.PHONY : files.i

# target to preprocess a source file
files.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/files.cpp.i
.PHONY : files.cpp.i

files.s: files.cpp.s
.PHONY : files.s

# target to generate assembly for a file
files.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/files.cpp.s
.PHONY : files.cpp.s

forms.o: forms.cpp.o
.PHONY : forms.o

# target to build an object file
forms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/forms.cpp.o
.PHONY : forms.cpp.o

forms.i: forms.cpp.i
.PHONY : forms.i

# target to preprocess a source file
forms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/forms.cpp.i
.PHONY : forms.cpp.i

forms.s: forms.cpp.s
.PHONY : forms.s

# target to generate assembly for a file
forms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/forms.cpp.s
.PHONY : forms.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/main.cpp.s
.PHONY : main.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/parser.cpp.s
.PHONY : parser.cpp.s

token.o: token.cpp.o
.PHONY : token.o

# target to build an object file
token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/token.cpp.o
.PHONY : token.cpp.o

token.i: token.cpp.i
.PHONY : token.i

# target to preprocess a source file
token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/token.cpp.i
.PHONY : token.cpp.i

token.s: token.cpp.s
.PHONY : token.s

# target to generate assembly for a file
token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/token.cpp.s
.PHONY : token.cpp.s

tokenizer.o: tokenizer.cpp.o
.PHONY : tokenizer.o

# target to build an object file
tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/tokenizer.cpp.o
.PHONY : tokenizer.cpp.o

tokenizer.i: tokenizer.cpp.i
.PHONY : tokenizer.i

# target to preprocess a source file
tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/tokenizer.cpp.i
.PHONY : tokenizer.cpp.i

tokenizer.s: tokenizer.cpp.s
.PHONY : tokenizer.s

# target to generate assembly for a file
tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/tokenizer.cpp.s
.PHONY : tokenizer.cpp.s

value.o: value.cpp.o
.PHONY : value.o

# target to build an object file
value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/value.cpp.o
.PHONY : value.cpp.o

value.i: value.cpp.i
.PHONY : value.i

# target to preprocess a source file
value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/value.cpp.i
.PHONY : value.cpp.i

value.s: value.cpp.s
.PHONY : value.s

# target to generate assembly for a file
value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/value.cpp.s
.PHONY : value.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lisp"
	@echo "... builtins.o"
	@echo "... builtins.i"
	@echo "... builtins.s"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... eval_env.o"
	@echo "... eval_env.i"
	@echo "... eval_env.s"
	@echo "... files.o"
	@echo "... files.i"
	@echo "... files.s"
	@echo "... forms.o"
	@echo "... forms.i"
	@echo "... forms.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... token.o"
	@echo "... token.i"
	@echo "... token.s"
	@echo "... tokenizer.o"
	@echo "... tokenizer.i"
	@echo "... tokenizer.s"
	@echo "... value.o"
	@echo "... value.i"
	@echo "... value.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

