# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter/CMakeFiles /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/浏览器下载/mini_lisp/rjsj_lisp_interpreter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lisp

# Build rule for target.
lisp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lisp
.PHONY : lisp

# fast build rule for target.
lisp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/build
.PHONY : lisp/fast

src/builtins.o: src/builtins.cpp.o
.PHONY : src/builtins.o

# target to build an object file
src/builtins.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/builtins.cpp.o
.PHONY : src/builtins.cpp.o

src/builtins.i: src/builtins.cpp.i
.PHONY : src/builtins.i

# target to preprocess a source file
src/builtins.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/builtins.cpp.i
.PHONY : src/builtins.cpp.i

src/builtins.s: src/builtins.cpp.s
.PHONY : src/builtins.s

# target to generate assembly for a file
src/builtins.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/builtins.cpp.s
.PHONY : src/builtins.cpp.s

src/error.o: src/error.cpp.o
.PHONY : src/error.o

# target to build an object file
src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/error.cpp.o
.PHONY : src/error.cpp.o

src/error.i: src/error.cpp.i
.PHONY : src/error.i

# target to preprocess a source file
src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/error.cpp.i
.PHONY : src/error.cpp.i

src/error.s: src/error.cpp.s
.PHONY : src/error.s

# target to generate assembly for a file
src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/error.cpp.s
.PHONY : src/error.cpp.s

src/eval_env.o: src/eval_env.cpp.o
.PHONY : src/eval_env.o

# target to build an object file
src/eval_env.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/eval_env.cpp.o
.PHONY : src/eval_env.cpp.o

src/eval_env.i: src/eval_env.cpp.i
.PHONY : src/eval_env.i

# target to preprocess a source file
src/eval_env.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/eval_env.cpp.i
.PHONY : src/eval_env.cpp.i

src/eval_env.s: src/eval_env.cpp.s
.PHONY : src/eval_env.s

# target to generate assembly for a file
src/eval_env.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/eval_env.cpp.s
.PHONY : src/eval_env.cpp.s

src/files.o: src/files.cpp.o
.PHONY : src/files.o

# target to build an object file
src/files.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/files.cpp.o
.PHONY : src/files.cpp.o

src/files.i: src/files.cpp.i
.PHONY : src/files.i

# target to preprocess a source file
src/files.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/files.cpp.i
.PHONY : src/files.cpp.i

src/files.s: src/files.cpp.s
.PHONY : src/files.s

# target to generate assembly for a file
src/files.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/files.cpp.s
.PHONY : src/files.cpp.s

src/forms.o: src/forms.cpp.o
.PHONY : src/forms.o

# target to build an object file
src/forms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/forms.cpp.o
.PHONY : src/forms.cpp.o

src/forms.i: src/forms.cpp.i
.PHONY : src/forms.i

# target to preprocess a source file
src/forms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/forms.cpp.i
.PHONY : src/forms.cpp.i

src/forms.s: src/forms.cpp.s
.PHONY : src/forms.s

# target to generate assembly for a file
src/forms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/forms.cpp.s
.PHONY : src/forms.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/token.o: src/token.cpp.o
.PHONY : src/token.o

# target to build an object file
src/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/token.cpp.o
.PHONY : src/token.cpp.o

src/token.i: src/token.cpp.i
.PHONY : src/token.i

# target to preprocess a source file
src/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/token.cpp.i
.PHONY : src/token.cpp.i

src/token.s: src/token.cpp.s
.PHONY : src/token.s

# target to generate assembly for a file
src/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/token.cpp.s
.PHONY : src/token.cpp.s

src/tokenizer.o: src/tokenizer.cpp.o
.PHONY : src/tokenizer.o

# target to build an object file
src/tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/tokenizer.cpp.o
.PHONY : src/tokenizer.cpp.o

src/tokenizer.i: src/tokenizer.cpp.i
.PHONY : src/tokenizer.i

# target to preprocess a source file
src/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/tokenizer.cpp.i
.PHONY : src/tokenizer.cpp.i

src/tokenizer.s: src/tokenizer.cpp.s
.PHONY : src/tokenizer.s

# target to generate assembly for a file
src/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/tokenizer.cpp.s
.PHONY : src/tokenizer.cpp.s

src/value.o: src/value.cpp.o
.PHONY : src/value.o

# target to build an object file
src/value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/value.cpp.o
.PHONY : src/value.cpp.o

src/value.i: src/value.cpp.i
.PHONY : src/value.i

# target to preprocess a source file
src/value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/value.cpp.i
.PHONY : src/value.cpp.i

src/value.s: src/value.cpp.s
.PHONY : src/value.s

# target to generate assembly for a file
src/value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lisp.dir/build.make CMakeFiles/lisp.dir/src/value.cpp.s
.PHONY : src/value.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lisp"
	@echo "... src/builtins.o"
	@echo "... src/builtins.i"
	@echo "... src/builtins.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/eval_env.o"
	@echo "... src/eval_env.i"
	@echo "... src/eval_env.s"
	@echo "... src/files.o"
	@echo "... src/files.i"
	@echo "... src/files.s"
	@echo "... src/forms.o"
	@echo "... src/forms.i"
	@echo "... src/forms.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/token.o"
	@echo "... src/token.i"
	@echo "... src/token.s"
	@echo "... src/tokenizer.o"
	@echo "... src/tokenizer.i"
	@echo "... src/tokenizer.s"
	@echo "... src/value.o"
	@echo "... src/value.i"
	@echo "... src/value.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

